affinity:
 nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: "app-confluent"
         operator: In
         values:
         - "cfkoperator"

imagePullSecretRef: <>

image:
  registry: <>:<>   # your local registry host[:port]
  repository: confluentinc/confluent-operator  
  pullPolicy: IfNotPresent
  tag: "0.1351.24"                               
