operatorPod:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "app-confluent"
            operator: In
            values:
            - "cmfoperator"

imagePullSecretRef: <>  

image:
  repository: <>:<>/confluentinc
  name: cp-cmf
  pullPolicy: IfNotPresent
  tag: "2.0.2"