operatorPod:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "app-confluent"
            operator: In
            values:
            - "flinkoperator"

imagePullSecrets:
  - name: <>

image:
  repository: <>:<>/confluentinc/cp-flink-kubernetes-operator
  tag: 1.12.1-cp1
  pullPolicy: IfNotPresent
